In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm
from pathlib import Path
import matplotlib.pyplot as plt
import cv2
import joblib
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input, Flatten, Conv2D, MaxPool2D, BatchNormalization, AveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.applications import ResNet50, VGG19
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm
import shutil

In [2]:
all_images =  "E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\ALL-DEFECT-IMAGES"
target_dir = Path(r"E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\PNG-PARENT")
excel_path = "E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\XL-structural-defect\ServiceOrderItemDetails.xlsx"
sel_cat = ["boxing","swimming"]
temp_cat = ["Windows-sliding door"]
png_file_dir = "E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\PNG-FILES"

In [3]:
class ImageSeparator:
    def __init__(self,images_dir,target_dir,excel_path):
        self.excel_path = excel_path
        self.images_dir = images_dir
        self.df = pd.read_excel(self.excel_path,sheet_name="Sheet1") 
        self.target_dir = target_dir
      
    def getFolderNameFromXL(self):
        categories = self.df['Category']
        unique_categories = []
        for i in categories:
            if i not in unique_categories:
                unique_categories.append(i)
        return unique_categories
    
    
    def folder_creation(self,parent_dir):
        #try:
        categories = self.getFolderNameFromXL()

        for category in categories:
            folder = category.replace("/","-").replace(" ","_")
            path = os.path.join(parent_dir,folder)
            os.mkdir(path)
            print(f"folder {folder} created")
        target_folders = os.listdir(parent_dir)
        return target_folders
#         except:
#             print("oops folder creation is unsuccessful")
            
    def append_files_based_on_category(self):
        #try:
        target_folders = os.listdir(self.target_dir)
        category = [category for category in self.df["Category"]]
        file_names = os.listdir(self.images_dir)

        for file in tqdm(file_names):
            head, tail = os.path.splitext(file)

            if tail in [".jpg", ".jpe", ".jpeg",".png"]:
                v = head.split("_")
                snum = int(v[0])
                onum = int(float(v[1]))
                cat = self.df[(self.df["Service Order Number"]==snum) & (self.df["Item No. Order Doc."]==onum)]['Category'].values
                for folder_name in target_folders:
                    print(folder_name)
                    old_name = folder_name.replace("-","/").replace("_"," ")
                    if (cat == old_name) :
                        print(cat)
                        shutil.copy(f"{self.images_dir}\{file}",f"{self.target_dir}\{folder_name}\{file}")

        print("********* all files has been classified **********")   
#         except:
#             print("oops... flailed to save files")
            
                
# image_separator = ImageSeparator(all_images,target_dir,excel_path)
# image_separator.append_files_based_on_category()
    

In [7]:

class PrepareDataForModel:
    def __init__(self,augmented=True):
        self.size = (260,260)
        self.augmented = augmented
        
        
    def set_resolution(modelName,imgPath):
        path = "E:\STRUCTURAL-DEFECT-DETECTION\Super-Resolution -Models\ESPCN_x3.pb"
        img = cv2.imread(imgPath)
        sr_model = cv2.dnn_superres.DnnSuperResImpl_create()
        sr_model.readModel(path)
        model.setModel("espcn",3)
        sr_image = sr_model.upsample(img)
        img = sr_image[:,:,::-1]
        return img
        
    
    def data_augmentation(self,parent_dir_path,aug_X,category):
        data = np.array(aug_X)
        print(data[0][0].shape)
        #save_path = r"E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\op"
        save_path = f'{os.path.join(parent_dir_path,category)}'
        dataGenerator = ImageDataGenerator(samplewise_center=True,
                                           rotation_range=40,vertical_flip=True,horizontal_flip=True,
                                           brightness_range=(0.5,1.5),width_shift_range= (0.5,1.5),
                                           height_shift_range=(0.5,1.5),rescale=1./255.) 
        print(f"file saving to{save_path}")
        epoch = 15
        for batch in tqdm(dataGenerator.flow(data,batch_size=16,save_to_dir=save_path,
                                             save_prefix='aug',save_format='jpe')):
            epoch -=1
            if epoch <=1:
                break
    
        
    def set_image_size(self,file_name,parent_dir_path,category):
        path = os.path.join(os.path.join(parent_dir_path,category),file_name)
        head, tail = os.path.splitext(file_name)
        if tail in [".jpe"]:
            file = cv2.imread(path)
            file = cv2.resize(file,self.size)
            return file
              
        
    def data_augmentation_driver(self,parent_dir_path):
        X =[]
        y = []
        print('data_augmentation_driver initiated....')
        parent_dir = os.listdir(parent_dir_path)
        for category in tqdm(parent_dir):
            if category in sel_cat:
                aug_X = []
                sub_dir = os.listdir(os.path.join(parent_dir_path,category))
                for file_name in sub_dir:
                    path = os.path.join(os.path.join(parent_dir_path,category),file_name)
                    print(path)

                    head, tail = os.path.splitext(file_name)
                    if tail in [".jpg"]:
                        #print(file_name,category)
                        file = cv2.imread(path)
                        file = cv2.cvtColor(file,cv2.COLOR_BGR2RGB)
                        file = cv2.resize(file,self.size)
                    if not self.augmented:
                        aug_X.append(file)
                    else:
                        X.extend([file])
                        y.extend([category])
                if len(aug_X):
                    print("...data augmentation started...")
                    self.data_augmentation(parent_dir_path,aug_X,category)

        if self.augmented:
            self.augmented = False
            print("data_augmentation_driver session ended....")
            print("features and labels are ready")
            X = np.array(X)
            y = np.array(y)
            return X,y
        self.augmented = True
        if self.augmented:
            return (self.data_augmentation_driver(parent_dir_path))
            
        print('************Anugmentation successfull **************')
    
    def save_features(self,X,y):
        path = r"C:\Users\sanketh\Desktop\JUPYTER\DEEP-LEARNING\test-cats\new_X.pickle"
        joblib.dump(X,path)
        path = r"C:\Users\sanketh\Desktop\JUPYTER\DEEP-LEARNING\test-cats\new_y.pickle"
        joblib.dump(y,path)

    def label_encoder(self,y):
        encoder = LabelEncoder()
        y = encoder.fit_transform(y)
        print("Values has been encoded")
        return y
    

In [8]:
am=PrepareDataForModel()
new_x,new_y = am.data_augmentation_driver(r"E:\DEEP-LEARNING\video-classification\images")

  0%|                                                                                            | 0/3 [00:00<?, ?it/s]

data_augmentation_driver initiated....
E:\DEEP-LEARNING\video-classification\images\boxing\00000000.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000001.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000003.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000004.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000005.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000006.png
E:\DEEP-LEARNING\video-classification\images\boxing\00000007.png
E:\DEEP-LEARNING\video-classification\images\boxing\00000009.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000011.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000012.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000013.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000014.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000015.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000016.jpg
E:\DEEP-LEARNING\video-classification\images\boxing

E:\DEEP-LEARNING\video-classification\images\boxing\00000148.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000149.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000150.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000152.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000153.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000154.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000155.jpeg
E:\DEEP-LEARNING\video-classification\images\boxing\00000156.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000157.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000158.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000159.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000160.jpeg
E:\DEEP-LEARNING\video-classification\images\boxing\00000161.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000162.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000163.jpg
E:\DEEP-LEARNING\video-

E:\DEEP-LEARNING\video-classification\images\boxing\00000308.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000309.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000310.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000312.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000313.JPG
E:\DEEP-LEARNING\video-classification\images\boxing\00000314.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000315.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000316.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000317.jpeg
E:\DEEP-LEARNING\video-classification\images\boxing\00000318.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000319.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000320.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000321.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000322.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000324.jpg
E:\DEEP-LEARNING\video-c

E:\DEEP-LEARNING\video-classification\images\boxing\00000458.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000459.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000460.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000461.png
E:\DEEP-LEARNING\video-classification\images\boxing\00000462.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000463.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000464.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000465.jpeg
E:\DEEP-LEARNING\video-classification\images\boxing\00000466.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000467.jpeg
E:\DEEP-LEARNING\video-classification\images\boxing\00000468.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000469.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000470.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000471.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000472.jpg
E:\DEEP-LEARNING\video-

E:\DEEP-LEARNING\video-classification\images\boxing\00000606.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000607.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000608.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000609.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000610.png
E:\DEEP-LEARNING\video-classification\images\boxing\00000611.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000612.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000613.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000614.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000615.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000617.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000618.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000619.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000620.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000621.jpg
E:\DEEP-LEARNING\video-cl

 33%|████████████████████████████                                                        | 1/3 [00:01<00:03,  1.88s/it]

E:\DEEP-LEARNING\video-classification\images\boxing\00000746.jpg
E:\DEEP-LEARNING\video-classification\images\boxing\00000747.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000000.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000001.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000002.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000003.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000005.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000006.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000007.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000008.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000009.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000010.png
E:\DEEP-LEARNING\video-classification\images\swimming\00000011.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000012.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000013.jpg

E:\DEEP-LEARNING\video-classification\images\swimming\00000140.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000141.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000142.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000143.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000144.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000145.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000146.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000147.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000148.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000149.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000150.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000151.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000152.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000153.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000154

E:\DEEP-LEARNING\video-classification\images\swimming\00000283.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000284.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000285.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000286.gif
E:\DEEP-LEARNING\video-classification\images\swimming\00000287.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000290.png
E:\DEEP-LEARNING\video-classification\images\swimming\00000291.JPG
E:\DEEP-LEARNING\video-classification\images\swimming\00000292.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000293.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000294.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000295.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000296.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000297.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000298.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000299

E:\DEEP-LEARNING\video-classification\images\swimming\00000431.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000432.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000433.jpeg
E:\DEEP-LEARNING\video-classification\images\swimming\00000434.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000435.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000436.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000437.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000438.png
E:\DEEP-LEARNING\video-classification\images\swimming\00000439.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000440.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000441.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000442.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000443.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000444.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\0000044

E:\DEEP-LEARNING\video-classification\images\swimming\00000577.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000578.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000579.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000580.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000581.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000582.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000583.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000584.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000585.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000586.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000587.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000588.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000589.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000590.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000591

100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.28s/it]

E:\DEEP-LEARNING\video-classification\images\swimming\00000699.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000700.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000701.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000702.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000703.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000704.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000705.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000706.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000707.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000708.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000709.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000710.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000712.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000714.jpg
E:\DEEP-LEARNING\video-classification\images\swimming\00000715

In [9]:
y

array(['boxing', 'boxing', 'boxing', ..., 'swimming', 'swimming',
       'swimming'], dtype='<U8')

In [33]:
y = am.label_encoder(y)

Values has been encoded


In [10]:
am.save_features(new_x,new_y)

In [160]:
path = "E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\Structural-Defect-Images-Categories\Other"
def test_external(path):
    other_list = []
    others = os.listdir(path)
    count = 0
    for img in others:
        img_path = os.path.join(path,img)
        img = cv2.imread(img_path)
        img = cv2.resize(img,(240,240))
        img = img/255.
        print(img.shape)
        other_list.extend([img])
        if(count > 20):
            break
        count +=1
    return other_list
        
        

## Adding column to excel


In [43]:
all_images = "E:\STRUCTURAL-DEFECT-DETECTION\STRUCTURAL-DEFECT-IMAGES\ALL-DEFECT-IMAGES-BACKUP"
df = pd.read_excel(excel_path,sheet_name="Sheet1")

def add_column(excel_path,images_path,df):
    df = pd.read_excel(excel_path,sheet_name="Sheet1")
    count = 0
    for file in tqdm(file_names):
                head, tail = os.path.splitext(file)
                name = f'{count}{tail}'
                new_name = os.path.join(all_images,name)
                old_name =os.path.join(all_images,file) 
                if tail in [".jpg", ".jpe", ".jpeg",".png"]:
                    v = head.split("_")
                    snum = int(v[0])
                    onum = int(float(v[1]))
                    index = df.index[(df["Service Order Number"]==snum) & (df["Item No. Order Doc."]==onum)][0]
                    df.iloc[index,0].fillna(value=0, inplace=True)
                    os.rename(old_name,new_name)
                    count +=1
    

In [96]:
import pandas as pd
df = pd.read_excel(excel_path,sheet_name="Sheet1")
df[(df["Service Order Number"]==8000086403) & (df["Item No. Order Doc."]==10)]["Defect Note 1"].values


array(['AC FILTER ACCESS - Unable to locate air conditioning filter'],
      dtype=object)

In [5]:
folder = Path(r"E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike")
for filename in (os.listdir(folder)):
    dst = f" {(filename)}.png"
    new = os.path.join(os.path.join(folder,dst))
    old = os.path.join(os.path.join(folder,filename))
    print(old)
    print(new)
    os.rename(old,new)

E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images127.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images127.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images128.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images128.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images129.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images129.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images130.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images130.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images131.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images131.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\images132.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ images132.jpg.png
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\indian-chief-bobber-dark-horse.jpg
E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\data\val\bike\ indian-chief-bobber-dark

In [2]:
path = r'E:\DEEP-LEARNING\YOLO\MASK\multi-cat'
file_names = os.listdir(path)
tpath = r'E:\DEEP-LEARNING\YOLO\MASK\copy'
for file in tqdm(file_names):
            head, tail = os.path.splitext(file)

            if tail in [".jpg"]:
                 shutil.copy(f"{path}\{file}",f"{tpath}\{file}")


100%|█████████████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 123.36it/s]


In [5]:
path = r"E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\multi_cat"
tpath = r"E:\DEEP-LEARNING\YOLO\Bike-Car-Yolo-V4\resize"
files = os.listdir(path)
for file in files:
    head,tail = os.path.splitext(file)
    if tail in [".png"]:
        img = cv2.imread(os.path.join(path,file))
        img = cv2.resize(img,(240,240))
        cv2.imwrite(os.path.join(tpath,file),img)
        

In [ ]:
path = r"E:\DEEP-LEARNING\YOLO\MASK\multi-cat"
files = os.listdir(path)
for file in tqdm(files):
    head, tail = os.path.splitext(file)
    if tail in [".jpg"]:

In [36]:
folder = r"E:\STRUCTURAL-DEFECT-DETECTION\TEST-DEFECT-DETECTION\painting\images"
files = os.listdir(folder)
count = 0
for file in files:
    head,tail = os.path.splitext(file)
    if tail not in [".jpg"]:
        dst = f" {(file)}.jpg"
        new = os.path.join(os.path.join(folder,dst))
        old = os.path.join(os.path.join(folder,file))
        os.rename(old,new)
        

In [35]:
folder = r"E:\STRUCTURAL-DEFECT-DETECTION\TEST-DEFECT-DETECTION\plumbing\Defect-Bound_Box\plumbing\yolo-format"
files = os.listdir(folder)
count = 0
for file in files:
    head,tail = os.path.splitext(file)
    name = f"plumbing-{count}.txt"
    new = os.path.join(os.path.join(folder,name))
    old = os.path.join(os.path.join(folder,file))
    os.rename(old,new)
    count+=1
   

In [38]:
folder = r"E:\STRUCTURAL-DEFECT-DETECTION\TEST-DEFECT-DETECTION\Bricklaying\brick-cat"
files = os.listdir(folder)
count = 0
for file in files:
    head,tail = os.path.splitext(file)
#     unwanted = head[-8:]
#     if ".jpe.png" in unwanted:
    print(file)

-old-red-brick-mold-covered-wall-the-surface-of-the-old-red-brick-1629278083.jpg
03fca2c3fb77d96088a68a052b685fab.jpg
0a8f7a0eb6d618090b8019c85f3328ea.jpg
10124611553_e532cb14b0_b.jpg
13310214825_1b78ab9dae_n.jpg
139364-592d8d566678d_img0601.jpg
14622665214_d11065c259.jpg
156719-59c123aa5bea7_cf8915c5-054a-482d-81e4-1c0e46b26868.jpg
169737669-texture-of-an-old-damaged-brick-wall-with-a-big-crack-in-it-as-a-vertical-background.jpg
200307282-001_XS.jpg
2017-07-27-12.b.jpg
240_F_219088579_KiWFjbjzOgfzdTTAA0nPU2ri1GshQkdb.jpg
360_F_163171838_XrS18tSEKA1uc4cutLdy29oJDFxBsvDF.jpg
360_F_28830296_MyGLN5p75o5HK09qrEoblpcHGOXcq2Q3.jpg
360_F_308745566_eEv5cxG0s8rhnCh2XReyS45GJ2tgBUDg.jpg
360_F_326802777_uO8hWRwWQME8bKlB63dLWOZosPaGW5YG.jpg
4718800725_5ce56b61ef_b.jpg
530f8a7150e27f2d7de724c1e4ed7bef.jpg
5693754541_ca31078388.jpg
6594037849_c778ed609a.jpg
7516e1d2e8bb6c2057e90f0f1983e31e.jpg
766-ad-sealing-weep-holes-brick-walls.jpg
81AEE7A9B4E381A8E383ACE383B3E382ACE381AEE5A381E381AEE3819DE381B0E

In [53]:
img_folder = r"E:\STRUCTURAL-DEFECT-DETECTION\TEST-DEFECT-DETECTION\Bricklaying\rash\image"
txt_folder = r"E:\STRUCTURAL-DEFECT-DETECTION\TEST-DEFECT-DETECTION\Bricklaying\rash\yolo"
img_files = os.listdir(img_folder)
txt_files = os.listdir(txt_folder)
counter = 1
for img,txt in zip(img_files,txt_files):
    im_head,im_tail = os.path.splitext(img)
    tx_head,tx_tail = os.path.splitext(txt)
    if im_head == tx_head:
        new_img =f"brick-{counter}.jpg" 
        new_txt = f"brick-{counter}.txt"
        old_im_name = os.path.join(img_folder,img)
        old_txt_name = os.path.join(txt_folder,txt)
        new_im_name = os.path.join(img_folder,new_img)
        new_txt_name = os.path.join(txt_folder,new_txt)
        os.rename(old_im_name,new_im_name)
        os.rename(old_txt_name,new_txt_name)
        counter +=1 

In [54]:
dic = {'san':1}

In [58]:
dic["san"]

1

In [59]:
class one:
    def __init__(self):
        pass
    def test(self):
        a = 1
        return a
    def temp(self):
        a = self.test()
        print(a)
        

In [60]:
o = one()

In [61]:
o.temp()

1


In [130]:
with open("test_file.txt","w") as file:
    file.write("classes = 3\n")
    file.write("filter = 14\n")


In [140]:
with open("test_file.txt") as file:
    print(file.read())

classes = 0
filter = 3


In [141]:
with open("test_file.txt","r") as file:
    line = file.readlines()
    print(line)
    line[0] = "classes = 10\n"
    file = open("test_file.txt", "w")
    file.writelines(line)
    file.close()
    

['classes = 0\n', 'filter = 3']


In [1]:
import cv2 as cv
cap = cv.VideoCapture(0)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    print(frame)
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv.imshow('frame', frame)
    if cv.waitKey(1) == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()

[[[ 87  90 106]
  [ 87  90 105]
  [ 88  92 105]
  ...
  [ 62  55  80]
  [ 68  55  81]
  [ 70  56  83]]

 [[ 88  91 107]
  [ 88  91 107]
  [ 89  92 108]
  ...
  [ 62  56  80]
  [ 67  57  83]
  [ 69  58  84]]

 [[ 89  92 108]
  [ 89  92 108]
  [ 89  92 108]
  ...
  [ 62  58  81]
  [ 65  57  83]
  [ 68  59  85]]

 ...

 [[175 162 189]
  [175 162 189]
  [175 162 189]
  ...
  [150 149 180]
  [149 148 180]
  [149 148 180]]

 [[173 163 189]
  [173 163 189]
  [173 163 189]
  ...
  [150 149 180]
  [149 148 180]
  [149 148 180]]

 [[173 163 189]
  [173 163 189]
  [173 163 189]
  ...
  [150 149 180]
  [149 148 180]
  [150 149 181]]]
[[[ 80  93  99]
  [ 84  94  99]
  [ 86  94 100]
  ...
  [ 64  60  62]
  [ 66  63  66]
  [ 66  63  66]]

 [[ 80  93  99]
  [ 83  93  98]
  [ 85  92  99]
  ...
  [ 64  59  63]
  [ 65  62  65]
  [ 66  63  66]]

 [[ 85  92  99]
  [ 85  92  99]
  [ 85  92  99]
  ...
  [ 65  60  65]
  [ 64  60  65]
  [ 64  60  65]]

 ...

 [[168 162 170]
  [170 163 171]
  [168 162 170]
  ..

[[[ 88  88  81]
  [ 87  85  79]
  [ 87  83  79]
  ...
  [ 52  60  64]
  [ 51  59  63]
  [ 49  57  61]]

 [[ 88  88  81]
  [ 87  86  80]
  [ 86  85  80]
  ...
  [ 51  59  62]
  [ 51  60  61]
  [ 50  59  60]]

 [[ 88  88  81]
  [ 87  86  80]
  [ 87  86  80]
  ...
  [ 48  59  60]
  [ 47  60  61]
  [ 45  59  60]]

 ...

 [[162 158 149]
  [161 156 149]
  [162 157 151]
  ...
  [140 143 136]
  [142 144 137]
  [143 145 138]]

 [[162 157 151]
  [162 157 151]
  [164 158 152]
  ...
  [140 143 134]
  [142 144 135]
  [145 147 137]]

 [[164 158 152]
  [164 158 152]
  [164 158 152]
  ...
  [141 143 134]
  [142 144 135]
  [146 148 138]]]
[[[ 85  92  84]
  [ 84  90  83]
  [ 84  91  83]
  ...
  [ 54  58  65]
  [ 56  59  66]
  [ 56  59  66]]

 [[ 85  92  84]
  [ 84  91  83]
  [ 83  89  82]
  ...
  [ 55  59  61]
  [ 55  59  61]
  [ 56  60  62]]

 [[ 84  91  83]
  [ 83  89  82]
  [ 82  88  81]
  ...
  [ 55  60  59]
  [ 55  60  59]
  [ 55  60  60]]

 ...

 [[161 158 152]
  [161 158 152]
  [161 158 152]
  ..

[[[ 89  89  69]
  [ 89  88  67]
  [ 89  87  67]
  ...
  [ 49  63  61]
  [ 47  64  58]
  [ 46  63  57]]

 [[ 87  89  72]
  [ 88  88  72]
  [ 88  87  71]
  ...
  [ 46  61  57]
  [ 45  62  56]
  [ 44  62  56]]

 [[ 84  87  75]
  [ 87  88  75]
  [ 89  88  74]
  ...
  [ 44  60  53]
  [ 42  60  52]
  [ 42  60  52]]

 ...

 [[164 158 154]
  [162 157 154]
  [160 156 154]
  ...
  [140 146 141]
  [140 146 141]
  [139 145 140]]

 [[164 158 154]
  [162 157 155]
  [160 156 156]
  ...
  [144 146 141]
  [144 145 141]
  [145 145 141]]

 [[161 158 154]
  [160 156 153]
  [160 156 154]
  ...
  [141 144 141]
  [144 144 144]
  [145 144 145]]]
[[[ 86  91  81]
  [ 83  87  75]
  [ 84  87  73]
  ...
  [ 67  60  67]
  [ 68  60  65]
  [ 67  59  64]]

 [[ 85  89  82]
  [ 84  87  79]
  [ 85  87  78]
  ...
  [ 66  59  63]
  [ 67  59  62]
  [ 66  58  61]]

 [[ 81  87  80]
  [ 82  88  80]
  [ 82  89  79]
  ...
  [ 63  58  59]
  [ 62  58  58]
  [ 61  57  57]]

 ...

 [[166 156 159]
  [166 156 159]
  [166 156 159]
  ..

[[[ 71  88  75]
  [ 70  89  77]
  [ 72  92  81]
  ...
  [ 62  56  63]
  [ 64  57  65]
  [ 65  59  66]]

 [[ 74  89  76]
  [ 73  89  77]
  [ 73  90  79]
  ...
  [ 60  57  62]
  [ 59  58  63]
  [ 59  58  63]]

 [[ 78  92  80]
  [ 73  89  77]
  [ 72  88  78]
  ...
  [ 56  58  60]
  [ 54  58  60]
  [ 55  59  61]]

 ...

 [[164 158 154]
  [164 158 154]
  [164 158 154]
  ...
  [142 144 140]
  [142 146 141]
  [143 147 142]]

 [[164 158 154]
  [164 158 154]
  [164 158 154]
  ...
  [142 145 142]
  [141 147 142]
  [141 147 142]]

 [[165 159 155]
  [164 157 156]
  [162 155 156]
  ...
  [143 146 146]
  [141 146 144]
  [142 148 145]]]
[[[ 81  91  88]
  [ 78  90  88]
  [ 73  87  86]
  ...
  [ 39  60  63]
  [ 35  60  60]
  [ 33  59  59]]

 [[ 80  90  85]
  [ 78  87  84]
  [ 77  86  85]
  ...
  [ 43  60  62]
  [ 41  60  58]
  [ 39  58  56]]

 [[ 82  90  85]
  [ 79  87  84]
  [ 77  86  85]
  ...
  [ 44  59  61]
  [ 40  56  55]
  [ 39  55  53]]

 ...

 [[166 158 152]
  [165 158 152]
  [164 158 152]
  ..

[[[ 84  85  80]
  [ 81  84  79]
  [ 80  85  80]
  ...
  [ 34  60  56]
  [ 39  61  55]
  [ 41  62  56]]

 [[ 82  85  80]
  [ 82  85  80]
  [ 82  85  80]
  ...
  [ 36  58  55]
  [ 39  60  58]
  [ 41  61  60]]

 [[ 80  86  78]
  [ 81  87  80]
  [ 81  87  80]
  ...
  [ 39  58  55]
  [ 41  60  58]
  [ 41  60  58]]

 ...

 [[161 155 151]
  [162 156 154]
  [162 155 156]
  ...
  [143 145 137]
  [142 144 137]
  [142 144 137]]

 [[161 154 155]
  [162 155 156]
  [162 155 156]
  ...
  [141 143 134]
  [141 143 134]
  [142 144 135]]

 [[160 156 156]
  [160 156 156]
  [161 157 157]
  ...
  [135 142 133]
  [134 141 131]
  [137 143 134]]]
[[[ 80  91  81]
  [ 76  88  78]
  [ 77  88  78]
  ...
  [ 47  60  71]
  [ 48  61  74]
  [ 48  61  74]]

 [[ 82  91  81]
  [ 79  88  78]
  [ 79  88  78]
  ...
  [ 47  61  68]
  [ 46  60  68]
  [ 46  60  68]]

 [[ 82  91  81]
  [ 79  88  78]
  [ 79  88  78]
  ...
  [ 47  61  64]
  [ 45  60  63]
  [ 43  59  62]]

 ...

 [[165 159 155]
  [166 160 156]
  [165 159 155]
  ..

[[[ 73  89  83]
  [ 77  89  84]
  [ 80  90  85]
  ...
  [ 55  56  60]
  [ 59  55  62]
  [ 61  56  64]]

 [[ 76  89  81]
  [ 79  90  83]
  [ 82  90  85]
  ...
  [ 53  58  59]
  [ 55  56  61]
  [ 55  56  61]]

 [[ 80  88  83]
  [ 81  89  84]
  [ 82  90  85]
  ...
  [ 52  60  61]
  [ 52  58  62]
  [ 51  57  61]]

 ...

 [[161 158 152]
  [161 158 152]
  [160 157 151]
  ...
  [139 144 138]
  [138 144 137]
  [139 145 138]]

 [[161 158 154]
  [161 158 153]
  [160 157 151]
  ...
  [138 144 138]
  [138 144 138]
  [139 145 140]]

 [[162 156 154]
  [162 158 154]
  [161 158 152]
  ...
  [138 143 139]
  [138 144 138]
  [138 144 138]]]
[[[ 82  87  84]
  [ 84  87  83]
  [ 86  88  81]
  ...
  [ 59  63  65]
  [ 58  62  64]
  [ 55  59  61]]

 [[ 83  86  81]
  [ 84  87  80]
  [ 86  88  79]
  ...
  [ 56  60  63]
  [ 56  60  62]
  [ 55  59  61]]

 [[ 85  87  80]
  [ 84  86  78]
  [ 85  87  78]
  ...
  [ 58  57  61]
  [ 59  59  61]
  [ 58  58  60]]

 ...

 [[162 156 154]
  [161 155 152]
  [162 156 152]
  ..

[[[ 91  91  89]
  [ 89  92  86]
  [ 85  92  82]
  ...
  [ 55  62  50]
  [ 54  62  47]
  [ 49  57  43]]

 [[ 90  90  90]
  [ 90  90  88]
  [ 89  90  85]
  ...
  [ 54  63  51]
  [ 53  61  46]
  [ 51  58  44]]

 [[ 86  87  83]
  [ 85  86  81]
  [ 85  86  81]
  ...
  [ 51  60  48]
  [ 51  61  46]
  [ 50  60  45]]

 ...

 [[161 159 150]
  [161 159 150]
  [163 160 151]
  ...
  [142 145 142]
  [144 145 141]
  [145 145 141]]

 [[161 159 150]
  [163 160 151]
  [163 160 151]
  ...
  [143 146 144]
  [144 145 141]
  [145 145 141]]

 [[163 160 151]
  [163 160 151]
  [163 160 151]
  ...
  [141 146 141]
  [142 146 141]
  [142 146 141]]]
[[[ 75  89  70]
  [ 76  90  71]
  [ 77  90  71]
  ...
  [ 53  61  61]
  [ 53  60  59]
  [ 51  58  57]]

 [[ 79  89  74]
  [ 80  90  75]
  [ 80  90  75]
  ...
  [ 50  61  58]
  [ 50  60  56]
  [ 49  58  55]]

 [[ 80  89  77]
  [ 80  90  79]
  [ 78  89  79]
  ...
  [ 46  62  56]
  [ 46  61  55]
  [ 43  58  52]]

 ...

 [[163 156 149]
  [161 155 147]
  [159 154 145]
  ..

[[[ 89  90  83]
  [ 89  90  84]
  [ 89  90  85]
  ...
  [ 54  58  53]
  [ 57  58  53]
  [ 57  58  53]]

 [[ 89  90  85]
  [ 87  88  85]
  [ 86  87  84]
  ...
  [ 54  58  53]
  [ 56  60  55]
  [ 55  58  53]]

 [[ 89  89  89]
  [ 88  87  87]
  [ 88  86  86]
  ...
  [ 56  58  53]
  [ 59  60  56]
  [ 57  58  53]]

 ...

 [[165 156 148]
  [163 156 149]
  [162 157 151]
  ...
  [143 145 139]
  [143 145 138]
  [143 145 138]]

 [[165 155 149]
  [165 154 147]
  [165 156 148]
  ...
  [145 144 141]
  [144 143 138]
  [145 144 139]]

 [[165 155 149]
  [165 154 147]
  [164 155 147]
  ...
  [145 144 141]
  [144 143 138]
  [145 144 139]]]
[[[ 78  90  75]
  [ 76  88  72]
  [ 75  88  71]
  ...
  [ 42  65  52]
  [ 43  63  52]
  [ 43  63  52]]

 [[ 77  89  76]
  [ 76  88  74]
  [ 75  88  73]
  ...
  [ 45  63  52]
  [ 45  63  52]
  [ 45  63  52]]

 [[ 77  89  76]
  [ 76  88  74]
  [ 75  88  73]
  ...
  [ 44  61  53]
  [ 46  61  53]
  [ 45  60  52]]

 ...

 [[163 160 153]
  [163 160 153]
  [163 160 153]
  ..

[[[ 80  92  89]
  [ 76  91  85]
  [ 70  88  80]
  ...
  [ 39  53  49]
  [ 37  52  47]
  [ 41  56  50]]

 [[ 82  92  89]
  [ 78  89  84]
  [ 73  87  78]
  ...
  [ 45  55  51]
  [ 44  54  49]
  [ 45  56  50]]

 [[ 83  91  86]
  [ 80  89  83]
  [ 75  86  78]
  ...
  [ 46  56  52]
  [ 45  55  50]
  [ 47  58  52]]

 ...

 [[162 156 152]
  [164 158 153]
  [162 156 152]
  ...
  [139 144 140]
  [139 145 140]
  [138 144 138]]

 [[160 157 152]
  [160 157 152]
  [159 155 151]
  ...
  [140 145 144]
  [139 144 143]
  [138 142 142]]

 [[160 157 152]
  [159 156 151]
  [158 154 150]
  ...
  [140 145 145]
  [139 144 143]
  [139 144 143]]]
[[[ 83  87  80]
  [ 84  87  80]
  [ 85  87  80]
  ...
  [ 41  57  48]
  [ 42  60  52]
  [ 44  63  54]]

 [[ 85  89  84]
  [ 86  89  83]
  [ 87  89  82]
  ...
  [ 41  57  48]
  [ 40  58  49]
  [ 42  60  52]]

 [[ 86  90  85]
  [ 88  91  86]
  [ 89  90  85]
  ...
  [ 44  55  48]
  [ 45  56  48]
  [ 47  58  50]]

 ...

 [[163 160 153]
  [161 158 152]
  [161 158 152]
  ..

[[[ 87  89  80]
  [ 85  86  75]
  [ 86  87  73]
  ...
  [ 53  63  50]
  [ 53  63  49]
  [ 52  62  47]]

 [[ 86  89  77]
  [ 84  87  74]
  [ 84  87  73]
  ...
  [ 53  62  51]
  [ 53  63  49]
  [ 52  62  47]]

 [[ 82  89  77]
  [ 80  87  73]
  [ 81  89  72]
  ...
  [ 53  63  50]
  [ 52  62  47]
  [ 51  61  46]]

 ...

 [[163 160 153]
  [163 159 154]
  [163 159 155]
  ...
  [137 148 140]
  [136 147 139]
  [136 147 139]]

 [[159 159 152]
  [159 158 152]
  [160 159 155]
  ...
  [136 147 139]
  [135 146 138]
  [136 147 139]]

 [[159 159 150]
  [159 159 152]
  [160 159 155]
  ...
  [137 145 138]
  [136 144 137]
  [137 145 138]]]
[[[ 78  90  87]
  [ 75  88  83]
  [ 74  87  81]
  ...
  [ 56  58  49]
  [ 52  55  45]
  [ 54  56  46]]

 [[ 79  88  87]
  [ 76  86  83]
  [ 77  87  81]
  ...
  [ 54  58  51]
  [ 51  55  48]
  [ 51  55  48]]

 [[ 79  86  83]
  [ 79  86  82]
  [ 78  86  80]
  ...
  [ 52  58  51]
  [ 49  56  48]
  [ 49  56  48]]

 ...

 [[164 155 156]
  [165 157 156]
  [162 156 154]
  ..

[[[ 83  91  86]
  [ 84  92  89]
  [ 83  90  90]
  ...
  [ 55  55  49]
  [ 55  54  45]
  [ 56  56  46]]

 [[ 82  90  85]
  [ 83  91  87]
  [ 81  89  86]
  ...
  [ 57  55  57]
  [ 57  55  53]
  [ 57  55  53]]

 [[ 82  90  85]
  [ 80  87  84]
  [ 79  86  85]
  ...
  [ 57  57  63]
  [ 57  56  61]
  [ 56  55  59]]

 ...

 [[162 157 151]
  [161 157 150]
  [160 158 149]
  ...
  [138 143 140]
  [138 142 142]
  [139 144 143]]

 [[160 158 149]
  [160 158 149]
  [160 158 149]
  ...
  [141 143 140]
  [143 143 143]
  [143 143 143]]

 [[160 158 149]
  [160 158 149]
  [159 157 148]
  ...
  [142 143 143]
  [143 143 143]
  [143 143 143]]]
[[[ 82  88  83]
  [ 82  88  83]
  [ 84  90  85]
  ...
  [ 58  62  57]
  [ 54  60  55]
  [ 53  59  53]]

 [[ 84  89  89]
  [ 82  88  86]
  [ 81  89  84]
  ...
  [ 56  60  55]
  [ 53  59  53]
  [ 53  59  53]]

 [[ 83  90  90]
  [ 81  88  88]
  [ 79  86  85]
  ...
  [ 52  57  52]
  [ 53  59  53]
  [ 53  59  53]]

 ...

 [[165 154 155]
  [165 154 155]
  [164 155 156]
  ..

[[[ 84  91  83]
  [ 84  87  84]
  [ 89  88  90]
  ...
  [ 50  63  55]
  [ 51  62  54]
  [ 51  62  54]]

 [[ 85  91  86]
  [ 86  89  87]
  [ 90  89  91]
  ...
  [ 52  62  53]
  [ 53  62  54]
  [ 53  62  54]]

 [[ 84  90  85]
  [ 85  91  88]
  [ 85  90  90]
  ...
  [ 52  59  52]
  [ 53  59  52]
  [ 53  59  52]]

 ...

 [[165 160 151]
  [164 160 152]
  [164 161 154]
  ...
  [146 145 141]
  [145 144 140]
  [145 144 140]]

 [[164 159 150]
  [165 161 153]
  [164 161 154]
  ...
  [145 145 141]
  [146 145 141]
  [147 145 141]]

 [[165 160 151]
  [164 160 151]
  [163 160 151]
  ...
  [144 147 142]
  [146 147 142]
  [146 147 142]]]
[[[ 78  87  86]
  [ 81  88  87]
  [ 82  87  84]
  ...
  [ 58  56  61]
  [ 59  56  61]
  [ 58  55  59]]

 [[ 80  88  83]
  [ 80  88  82]
  [ 82  88  81]
  ...
  [ 58  58  59]
  [ 57  57  57]
  [ 57  57  57]]

 [[ 81  87  80]
  [ 84  88  81]
  [ 86  88  81]
  ...
  [ 55  60  54]
  [ 53  59  53]
  [ 53  59  53]]

 ...

 [[159 158 154]
  [158 157 153]
  [158 156 154]
  ..

[[[ 77  91  67]
  [ 76  90  64]
  [ 79  92  63]
  ...
  [ 69  61  73]
  [ 68  61  73]
  [ 67  60  72]]

 [[ 78  91  72]
  [ 79  92  70]
  [ 79  91  67]
  ...
  [ 67  61  68]
  [ 67  61  68]
  [ 66  60  67]]

 [[ 80  93  76]
  [ 81  93  76]
  [ 79  89  72]
  ...
  [ 63  60  62]
  [ 64  61  64]
  [ 62  59  61]]

 ...

 [[161 158 152]
  [164 159 153]
  [165 159 153]
  ...
  [142 147 142]
  [141 147 142]
  [141 147 142]]

 [[163 160 151]
  [163 160 151]
  [163 160 151]
  ...
  [139 146 141]
  [139 147 142]
  [140 148 143]]

 [[163 160 151]
  [163 160 151]
  [163 160 151]
  ...
  [140 146 142]
  [138 146 143]
  [140 148 145]]]
[[[ 88  90  72]
  [ 87  90  72]
  [ 89  93  74]
  ...
  [ 42  63  48]
  [ 45  64  49]
  [ 45  64  49]]

 [[ 85  89  72]
  [ 85  90  74]
  [ 86  92  78]
  ...
  [ 44  61  49]
  [ 46  62  49]
  [ 46  62  49]]

 [[ 85  88  74]
  [ 84  89  77]
  [ 84  91  81]
  ...
  [ 49  60  51]
  [ 46  58  48]
  [ 46  58  47]]

 ...

 [[167 159 155]
  [167 159 155]
  [167 159 155]
  ..

  [141 142 136]]]
[[[ 82  92  89]
  [ 80  92  91]
  [ 77  90  91]
  ...
  [ 58  57  41]
  [ 58  57  39]
  [ 62  62  44]]

 [[ 82  92  89]
  [ 82  92  91]
  [ 80  89  90]
  ...
  [ 57  57  42]
  [ 57  58  42]
  [ 59  61  44]]

 [[ 80  90  87]
  [ 80  89  89]
  [ 80  89  90]
  ...
  [ 55  58  44]
  [ 54  57  41]
  [ 55  59  42]]

 ...

 [[161 158 154]
  [161 158 153]
  [161 158 152]
  ...
  [141 146 141]
  [142 146 141]
  [144 147 142]]

 [[161 157 157]
  [161 157 155]
  [161 158 154]
  ...
  [143 146 141]
  [144 145 141]
  [145 145 141]]

 [[164 155 161]
  [162 155 159]
  [165 157 160]
  ...
  [144 146 140]
  [143 145 138]
  [143 145 138]]]
[[[ 81  88  78]
  [ 81  88  78]
  [ 80  86  77]
  ...
  [ 54  61  56]
  [ 54  60  53]
  [ 46  52  44]]

 [[ 81  87  80]
  [ 81  87  80]
  [ 81  87  80]
  ...
  [ 54  61  57]
  [ 52  58  51]
  [ 48  55  47]]

 [[ 81  87  80]
  [ 82  88  81]
  [ 82  88  81]
  ...
  [ 52  60  55]
  [ 48  57  49]
  [ 46  55  47]]

 ...

 [[165 159 153]
  [162 158 152]
  

[[[ 79  91  90]
  [ 81  91  90]
  [ 82  89  89]
  ...
  [ 40  57  58]
  [ 40  56  57]
  [ 40  56  57]]

 [[ 81  91  88]
  [ 82  89  88]
  [ 83  88  87]
  ...
  [ 43  58  59]
  [ 42  55  57]
  [ 42  55  57]]

 [[ 82  90  85]
  [ 82  89  84]
  [ 82  88  83]
  ...
  [ 44  58  59]
  [ 42  55  57]
  [ 42  55  57]]

 ...

 [[165 156 146]
  [165 158 146]
  [164 160 146]
  ...
  [143 144 140]
  [144 145 141]
  [144 145 141]]

 [[165 156 146]
  [165 158 146]
  [162 159 145]
  ...
  [143 145 138]
  [143 145 138]
  [144 146 139]]

 [[165 157 144]
  [166 158 145]
  [164 158 145]
  ...
  [141 145 138]
  [141 145 138]
  [142 146 139]]]
[[[ 81  94  77]
  [ 82  94  78]
  [ 82  92  78]
  ...
  [ 58  55  51]
  [ 57  56  51]
  [ 54  53  49]]

 [[ 83  91  77]
  [ 84  92  78]
  [ 83  91  77]
  ...
  [ 57  56  51]
  [ 57  56  51]
  [ 55  53  49]]

 [[ 82  90  75]
  [ 82  90  75]
  [ 82  90  75]
  ...
  [ 56  55  49]
  [ 56  55  48]
  [ 56  55  48]]

 ...

 [[164 156 143]
  [163 157 144]
  [161 157 144]
  ..

[[[ 78  90  77]
  [ 79  91  79]
  [ 78  89  79]
  ...
  [ 62  59  54]
  [ 59  56  40]
  [ 59  56  39]]

 [[ 79  88  76]
  [ 81  90  79]
  [ 81  90  80]
  ...
  [ 58  60  54]
  [ 58  58  47]
  [ 56  56  44]]

 [[ 79  88  76]
  [ 81  90  79]
  [ 82  91  81]
  ...
  [ 58  60  54]
  [ 60  60  51]
  [ 59  59  50]]

 ...

 [[160 157 152]
  [159 156 151]
  [159 155 151]
  ...
  [145 147 141]
  [144 145 141]
  [145 145 141]]

 [[159 155 151]
  [159 155 151]
  [159 155 151]
  ...
  [145 147 141]
  [146 147 142]
  [145 145 141]]

 [[159 155 151]
  [160 155 151]
  [161 155 151]
  ...
  [145 147 141]
  [146 147 142]
  [146 147 142]]]
[[[ 86  88  79]
  [ 85  87  77]
  [ 85  87  78]
  ...
  [ 60  65  62]
  [ 58  65  64]
  [ 55  62  62]]

 [[ 86  88  79]
  [ 85  87  78]
  [ 85  87  78]
  ...
  [ 57  63  58]
  [ 57  65  59]
  [ 54  62  57]]

 [[ 84  89  79]
  [ 83  89  79]
  [ 82  89  79]
  ...
  [ 54  61  56]
  [ 54  62  57]
  [ 52  60  55]]

 ...

 [[166 158 152]
  [165 158 152]
  [164 158 152]
  ..

[[[ 78  87  68]
  [ 80  86  67]
  [ 83  87  68]
  ...
  [ 46  59  53]
  [ 44  59  53]
  [ 43  58  52]]

 [[ 81  87  70]
  [ 82  87  70]
  [ 84  88  71]
  ...
  [ 45  56  55]
  [ 44  56  55]
  [ 44  56  55]]

 [[ 82  88  71]
  [ 82  87  70]
  [ 84  88  71]
  ...
  [ 45  54  54]
  [ 46  56  55]
  [ 46  56  55]]

 ...

 [[161 157 144]
  [159 155 142]
  [160 156 145]
  ...
  [144 144 147]
  [144 144 146]
  [144 144 146]]

 [[160 157 141]
  [160 157 141]
  [160 157 141]
  ...
  [141 144 145]
  [140 145 144]
  [140 145 144]]

 [[157 156 138]
  [158 157 140]
  [159 158 142]
  ...
  [140 146 146]
  [139 146 146]
  [138 145 144]]]
[[[ 78  87  68]
  [ 80  86  67]
  [ 83  87  68]
  ...
  [ 46  59  53]
  [ 44  59  53]
  [ 43  58  52]]

 [[ 81  87  70]
  [ 82  87  70]
  [ 84  88  71]
  ...
  [ 45  56  55]
  [ 44  56  55]
  [ 44  56  55]]

 [[ 82  88  71]
  [ 82  87  70]
  [ 84  88  71]
  ...
  [ 45  54  54]
  [ 46  56  55]
  [ 46  56  55]]

 ...

 [[161 157 144]
  [159 155 142]
  [160 156 145]
  ..

[[[ 82  89  79]
  [ 84  91  82]
  [ 85  92  84]
  ...
  [ 54  65  47]
  [ 54  64  50]
  [ 52  62  48]]

 [[ 82  89  77]
  [ 82  90  80]
  [ 83  92  84]
  ...
  [ 54  63  49]
  [ 54  63  53]
  [ 54  63  54]]

 [[ 79  88  78]
  [ 81  90  81]
  [ 83  92  84]
  ...
  [ 52  60  48]
  [ 53  62  52]
  [ 54  63  54]]

 ...

 [[162 158 147]
  [161 157 145]
  [161 157 144]
  ...
  [142 148 145]
  [142 148 145]
  [141 146 144]]

 [[162 158 149]
  [162 158 147]
  [162 159 145]
  ...
  [141 146 147]
  [141 145 147]
  [141 145 147]]

 [[164 157 151]
  [165 158 150]
  [164 159 148]
  ...
  [141 146 147]
  [141 145 147]
  [141 145 147]]]
[[[ 82  90  75]
  [ 82  89  77]
  [ 81  88  78]
  ...
  [ 54  59  53]
  [ 54  62  57]
  [ 56  65  59]]

 [[ 83  90  78]
  [ 83  90  79]
  [ 81  88  78]
  ...
  [ 52  59  53]
  [ 54  63  55]
  [ 55  64  56]]

 [[ 82  89  77]
  [ 82  89  78]
  [ 82  89  79]
  ...
  [ 52  60  54]
  [ 53  62  54]
  [ 52  61  53]]

 ...

 [[163 155 153]
  [162 155 152]
  [161 155 151]
  ..

[[[ 89  90  85]
  [ 89  88  84]
  [ 87  86  81]
  ...
  [ 59  54  57]
  [ 61  56  59]
  [ 61  56  59]]

 [[ 90  91  84]
  [ 87  89  82]
  [ 85  87  80]
  ...
  [ 60  55  57]
  [ 59  54  55]
  [ 59  54  55]]

 [[ 90  91  84]
  [ 89  90  83]
  [ 86  88  81]
  ...
  [ 58  55  57]
  [ 56  53  54]
  [ 55  52  52]]

 ...

 [[165 158 158]
  [166 159 160]
  [166 159 160]
  ...
  [140 146 142]
  [139 145 140]
  [139 145 140]]

 [[163 158 158]
  [163 158 158]
  [163 158 158]
  ...
  [139 144 140]
  [140 146 141]
  [139 145 140]]

 [[163 158 158]
  [163 158 158]
  [163 158 158]
  ...
  [139 144 140]
  [139 145 140]
  [140 146 141]]]
[[[ 88  93  81]
  [ 86  89  76]
  [ 87  88  74]
  ...
  [ 64  61  47]
  [ 64  61  52]
  [ 65  62  54]]

 [[ 83  90  80]
  [ 84  89  79]
  [ 86  88  79]
  ...
  [ 64  61  46]
  [ 64  62  49]
  [ 63  62  49]]

 [[ 81  88  78]
  [ 82  89  80]
  [ 84  91  83]
  ...
  [ 60  59  45]
  [ 59  58  44]
  [ 61  60  46]]

 ...

 [[168 156 157]
  [167 155 156]
  [167 155 156]
  ..

[[[ 80  88  81]
  [ 79  89  80]
  [ 80  91  81]
  ...
  [ 61  59  65]
  [ 64  60  65]
  [ 62  58  63]]

 [[ 82  91  81]
  [ 82  91  81]
  [ 81  90  80]
  ...
  [ 57  58  63]
  [ 61  60  62]
  [ 60  59  61]]

 [[ 82  91  81]
  [ 82  91  81]
  [ 82  91  81]
  ...
  [ 53  58  60]
  [ 54  58  60]
  [ 53  57  59]]

 ...

 [[164 158 152]
  [164 158 153]
  [164 158 154]
  ...
  [140 146 140]
  [140 146 141]
  [140 146 141]]

 [[162 156 152]
  [163 158 154]
  [165 159 155]
  ...
  [140 146 141]
  [140 146 141]
  [141 147 142]]

 [[162 156 152]
  [163 158 154]
  [164 158 154]
  ...
  [141 146 142]
  [141 147 142]
  [141 147 142]]]
[[[ 87  86  81]
  [ 87  86  81]
  [ 87  86  80]
  ...
  [ 60  61  65]
  [ 58  61  65]
  [ 56  60  64]]

 [[ 86  85  80]
  [ 86  85  80]
  [ 86  85  78]
  ...
  [ 61  61  65]
  [ 60  61  65]
  [ 58  60  64]]

 [[ 85  87  80]
  [ 84  85  79]
  [ 84  85  78]
  ...
  [ 58  58  60]
  [ 61  60  62]
  [ 59  59  61]]

 ...

 [[162 158 149]
  [162 158 148]
  [161 157 146]
  ..

[[[ 86  89  87]
  [ 83  88  82]
  [ 84  91  81]
  ...
  [ 51  58  60]
  [ 58  58  60]
  [ 59  58  60]]

 [[ 89  89  87]
  [ 87  90  85]
  [ 84  91  83]
  ...
  [ 50  59  60]
  [ 54  58  60]
  [ 55  58  60]]

 [[ 86  89  89]
  [ 85  90  86]
  [ 82  88  81]
  ...
  [ 50  57  59]
  [ 51  57  59]
  [ 49  55  57]]

 ...

 [[162 157 151]
  [162 158 152]
  [160 157 151]
  ...
  [141 144 145]
  [139 144 143]
  [139 144 143]]

 [[162 156 152]
  [160 155 151]
  [159 155 151]
  ...
  [142 144 146]
  [140 144 146]
  [139 143 145]]

 [[164 156 159]
  [161 156 155]
  [159 155 151]
  ...
  [142 144 147]
  [140 144 146]
  [139 143 145]]]
[[[ 81  88  78]
  [ 81  88  76]
  [ 81  89  74]
  ...
  [ 65  60  55]
  [ 65  62  55]
  [ 65  62  55]]

 [[ 82  88  81]
  [ 82  88  80]
  [ 83  90  80]
  ...
  [ 62  60  55]
  [ 61  62  55]
  [ 60  62  55]]

 [[ 84  87  83]
  [ 83  87  83]
  [ 84  90  85]
  ...
  [ 57  61  56]
  [ 56  63  55]
  [ 56  63  55]]

 ...

 [[164 157 151]
  [165 158 152]
  [164 158 152]
  ..

[[[ 79  87  81]
  [ 79  86  82]
  [ 79  86  83]
  ...
  [ 71  59  56]
  [ 70  59  56]
  [ 69  58  55]]

 [[ 79  87  81]
  [ 79  87  82]
  [ 79  87  81]
  ...
  [ 67  60  56]
  [ 66  60  56]
  [ 66  60  56]]

 [[ 79  87  81]
  [ 80  88  83]
  [ 80  88  83]
  ...
  [ 64  60  56]
  [ 65  61  57]
  [ 64  60  56]]

 ...

 [[164 158 154]
  [164 158 153]
  [164 158 152]
  ...
  [140 146 140]
  [140 146 141]
  [140 146 141]]

 [[162 156 152]
  [161 156 150]
  [161 156 149]
  ...
  [139 146 137]
  [140 146 139]
  [140 146 139]]

 [[161 155 153]
  [161 155 151]
  [161 156 149]
  ...
  [139 146 135]
  [140 147 137]
  [140 147 137]]]
[[[ 77  86  83]
  [ 75  84  82]
  [ 78  84  84]
  ...
  [ 41  60  51]
  [ 40  60  52]
  [ 41  62  53]]

 [[ 80  88  83]
  [ 79  85  80]
  [ 80  85  80]
  ...
  [ 46  60  50]
  [ 47  60  52]
  [ 45  59  51]]

 [[ 80  88  81]
  [ 79  86  78]
  [ 80  86  78]
  ...
  [ 54  59  51]
  [ 51  57  49]
  [ 50  57  49]]

 ...

 [[164 156 159]
  [164 156 159]
  [164 156 159]
  ..

[[[ 78  95  71]
  [ 76  94  73]
  [ 74  94  76]
  ...
  [ 52  61  57]
  [ 50  61  53]
  [ 47  58  50]]

 [[ 78  94  74]
  [ 77  93  76]
  [ 76  93  78]
  ...
  [ 49  62  56]
  [ 47  62  54]
  [ 44  60  51]]

 [[ 78  92  80]
  [ 77  92  80]
  [ 76  92  81]
  ...
  [ 50  60  56]
  [ 52  63  55]
  [ 50  61  53]]

 ...

 [[163 159 155]
  [161 158 153]
  [161 158 152]
  ...
  [140 146 139]
  [139 145 138]
  [140 146 139]]

 [[163 160 153]
  [160 159 151]
  [159 159 150]
  ...
  [140 146 139]
  [139 145 138]
  [140 146 139]]

 [[161 159 148]
  [161 159 148]
  [161 159 148]
  ...
  [142 146 139]
  [140 146 139]
  [140 146 139]]]
[[[ 78  87  77]
  [ 76  86  74]
  [ 78  88  73]
  ...
  [ 47  53  51]
  [ 49  54  54]
  [ 53  57  57]]

 [[ 80  86  77]
  [ 80  86  77]
  [ 80  86  77]
  ...
  [ 49  55  51]
  [ 49  55  52]
  [ 53  58  55]]

 [[ 81  87  80]
  [ 80  86  78]
  [ 80  86  77]
  ...
  [ 51  56  52]
  [ 51  56  51]
  [ 54  60  55]]

 ...

 [[160 157 151]
  [160 157 151]
  [161 158 152]
  ..

[[[ 86  90  72]
  [ 86  90  73]
  [ 89  92  76]
  ...
  [ 61  59  64]
  [ 63  59  64]
  [ 63  59  64]]

 [[ 86  90  72]
  [ 87  91  75]
  [ 89  92  78]
  ...
  [ 61  60  63]
  [ 63  60  62]
  [ 63  60  62]]

 [[ 84  88  71]
  [ 86  89  76]
  [ 89  91  81]
  ...
  [ 64  60  62]
  [ 64  58  61]
  [ 63  57  60]]

 ...

 [[161 158 154]
  [162 158 154]
  [164 158 154]
  ...
  [142 145 144]
  [140 145 144]
  [140 145 144]]

 [[161 158 152]
  [161 158 153]
  [163 159 155]
  ...
  [142 145 142]
  [141 147 142]
  [140 146 141]]

 [[161 158 152]
  [162 160 153]
  [163 160 153]
  ...
  [141 146 141]
  [141 147 142]
  [141 147 142]]]
[[[ 86  94  88]
  [ 85  93  86]
  [ 84  91  83]
  ...
  [ 51  57  44]
  [ 55  57  48]
  [ 60  61  52]]

 [[ 88  91  86]
  [ 88  91  85]
  [ 86  88  81]
  ...
  [ 52  57  49]
  [ 53  57  49]
  [ 56  60  53]]

 [[ 86  88  81]
  [ 87  88  81]
  [ 87  86  80]
  ...
  [ 49  56  52]
  [ 51  56  51]
  [ 53  59  53]]

 ...

 [[164 159 160]
  [163 159 160]
  [162 159 160]
  ..

[[[ 77  87  81]
  [ 76  86  83]
  [ 78  87  86]
  ...
  [ 45  61  52]
  [ 43  61  53]
  [ 44  62  54]]

 [[ 78  88  84]
  [ 79  87  85]
  [ 80  87  86]
  ...
  [ 45  61  54]
  [ 42  60  53]
  [ 43  61  55]]

 [[ 78  88  84]
  [ 79  87  85]
  [ 79  86  85]
  ...
  [ 46  62  56]
  [ 43  61  55]
  [ 40  57  51]]

 ...

 [[164 158 152]
  [164 158 152]
  [164 158 152]
  ...
  [140 145 143]
  [140 145 143]
  [140 145 143]]

 [[164 158 152]
  [162 157 151]
  [162 157 151]
  ...
  [141 144 142]
  [143 143 143]
  [143 143 143]]

 [[162 158 149]
  [161 156 148]
  [161 156 148]
  ...
  [141 144 142]
  [142 142 142]
  [142 142 142]]]
[[[ 76  92  81]
  [ 77  90  81]
  [ 78  89  81]
  ...
  [ 64  64  48]
  [ 64  65  49]
  [ 61  63  47]]

 [[ 80  91  83]
  [ 79  90  82]
  [ 78  89  81]
  ...
  [ 63  63  50]
  [ 62  62  49]
  [ 62  62  49]]

 [[ 81  92  84]
  [ 79  90  82]
  [ 78  89  81]
  ...
  [ 58  61  48]
  [ 55  58  44]
  [ 56  59  45]]

 ...

 [[164 158 152]
  [163 158 151]
  [164 159 150]
  ..

[[[ 79  93  81]
  [ 82  94  84]
  [ 84  93  85]
  ...
  [ 57  62  52]
  [ 56  63  53]
  [ 55  62  52]]

 [[ 79  90  82]
  [ 81  91  84]
  [ 83  91  86]
  ...
  [ 56  62  52]
  [ 55  62  52]
  [ 54  61  51]]

 [[ 79  87  81]
  [ 80  88  82]
  [ 80  88  83]
  ...
  [ 53  61  51]
  [ 51  60  50]
  [ 48  58  48]]

 ...

 [[161 158 152]
  [161 158 152]
  [161 158 152]
  ...
  [142 145 138]
  [143 145 138]
  [143 145 138]]

 [[161 158 152]
  [162 158 152]
  [161 158 152]
  ...
  [141 146 136]
  [143 145 136]
  [143 145 136]]

 [[158 157 151]
  [158 157 151]
  [159 159 152]
  ...
  [139 146 136]
  [139 146 136]
  [139 146 136]]]
[[[ 79  93  81]
  [ 82  94  84]
  [ 84  93  85]
  ...
  [ 57  62  52]
  [ 56  63  53]
  [ 55  62  52]]

 [[ 79  90  82]
  [ 81  91  84]
  [ 83  91  86]
  ...
  [ 56  62  52]
  [ 55  62  52]
  [ 54  61  51]]

 [[ 79  87  81]
  [ 80  88  82]
  [ 80  88  83]
  ...
  [ 53  61  51]
  [ 51  60  50]
  [ 48  58  48]]

 ...

 [[161 158 152]
  [161 158 152]
  [161 158 152]
  ..

[[[ 85  91  88]
  [ 85  91  86]
  [ 85  92  84]
  ...
  [ 53  60  53]
  [ 53  62  54]
  [ 53  62  54]]

 [[ 89  90  85]
  [ 90  91  85]
  [ 89  90  83]
  ...
  [ 52  59  51]
  [ 53  62  52]
  [ 53  62  52]]

 [[ 86  87  83]
  [ 85  86  81]
  [ 85  86  81]
  ...
  [ 51  59  49]
  [ 52  61  51]
  [ 52  61  51]]

 ...

 [[164 158 152]
  [163 158 152]
  [161 158 152]
  ...
  [138 145 139]
  [138 144 137]
  [138 144 137]]

 [[160 157 151]
  [159 158 150]
  [158 158 149]
  ...
  [137 144 137]
  [137 143 136]
  [138 144 137]]

 [[158 157 151]
  [158 157 151]
  [157 156 149]
  ...
  [136 144 133]
  [137 143 134]
  [138 145 135]]]
[[[ 83  88  76]
  [ 82  88  77]
  [ 82  89  79]
  ...
  [ 37  61  56]
  [ 32  59  49]
  [ 31  59  49]]

 [[ 83  87  78]
  [ 82  87  79]
  [ 81  87  80]
  ...
  [ 41  59  55]
  [ 37  57  48]
  [ 37  57  48]]

 [[ 83  86  81]
  [ 83  88  83]
  [ 81  87  81]
  ...
  [ 41  56  51]
  [ 40  55  47]
  [ 39  54  46]]

 ...

 [[164 157 155]
  [162 157 155]
  [161 157 155]
  ..

[[[ 85  85  76]
  [ 87  87  78]
  [ 88  88  79]
  ...
  [ 60  59  49]
  [ 60  60  51]
  [ 62  61  52]]

 [[ 84  86  77]
  [ 85  87  79]
  [ 86  88  81]
  ...
  [ 55  57  48]
  [ 56  58  49]
  [ 58  60  51]]

 [[ 82  86  77]
  [ 84  87  79]
  [ 85  87  80]
  ...
  [ 53  55  48]
  [ 54  55  48]
  [ 55  56  49]]

 ...

 [[160 157 151]
  [160 157 151]
  [160 157 151]
  ...
  [140 146 141]
  [139 145 140]
  [139 145 140]]

 [[159 156 149]
  [159 156 149]
  [159 156 149]
  ...
  [138 144 137]
  [138 144 137]
  [139 145 138]]

 [[159 156 149]
  [158 155 148]
  [158 155 148]
  ...
  [139 143 136]
  [140 144 137]
  [141 145 138]]]
[[[ 81  88  76]
  [ 88  92  82]
  [ 91  93  84]
  ...
  [ 61  60  63]
  [ 62  59  61]
  [ 58  55  58]]

 [[ 82  89  77]
  [ 85  91  80]
  [ 88  92  82]
  ...
  [ 60  60  61]
  [ 58  58  58]
  [ 57  57  57]]

 [[ 82  89  77]
  [ 83  90  79]
  [ 84  91  81]
  ...
  [ 54  58  59]
  [ 53  57  57]
  [ 53  58  57]]

 ...

 [[165 156 148]
  [165 156 148]
  [165 156 148]
  ..

[[[ 86  90  85]
  [ 87  89  83]
  [ 85  87  80]
  ...
  [ 55  56  56]
  [ 54  53  55]
  [ 57  56  59]]

 [[ 85  89  84]
  [ 85  88  82]
  [ 85  87  80]
  ...
  [ 53  57  55]
  [ 51  54  54]
  [ 53  55  55]]

 [[ 83  87  80]
  [ 84  87  80]
  [ 85  87  80]
  ...
  [ 52  57  54]
  [ 49  54  54]
  [ 49  54  54]]

 ...

 [[169 159 153]
  [168 158 152]
  [169 159 153]
  ...
  [139 146 141]
  [140 146 141]
  [140 146 141]]

 [[168 157 154]
  [168 157 154]
  [168 157 154]
  ...
  [139 146 141]
  [139 145 140]
  [139 145 140]]

 [[169 156 152]
  [168 156 152]
  [168 157 154]
  ...
  [139 146 141]
  [140 146 141]
  [140 146 141]]]
[[[ 74  84  83]
  [ 77  86  83]
  [ 78  88  83]
  ...
  [ 64  56  69]
  [ 64  56  70]
  [ 65  57  72]]

 [[ 78  84  84]
  [ 78  86  83]
  [ 78  88  83]
  ...
  [ 60  56  65]
  [ 60  56  65]
  [ 60  56  66]]

 [[ 77  87  81]
  [ 78  88  83]
  [ 77  87  81]
  ...
  [ 58  56  61]
  [ 55  54  58]
  [ 56  55  59]]

 ...

 [[161 155 153]
  [160 155 151]
  [160 157 151]
  ..

[[[ 87  92  87]
  [ 88  93  89]
  [ 87  92  87]
  ...
  [ 53  63  54]
  [ 52  60  53]
  [ 51  59  52]]

 [[ 87  92  87]
  [ 88  93  89]
  [ 87  92  87]
  ...
  [ 52  63  55]
  [ 53  61  56]
  [ 52  60  55]]

 [[ 85  91  86]
  [ 87  93  86]
  [ 85  92  84]
  ...
  [ 51  61  58]
  [ 53  60  59]
  [ 52  59  58]]

 ...

 [[162 155 156]
  [161 154 154]
  [162 156 154]
  ...
  [144 145 141]
  [144 145 141]
  [144 145 141]]

 [[162 155 156]
  [161 154 155]
  [162 155 156]
  ...
  [144 145 141]
  [144 145 141]
  [144 145 141]]

 [[166 157 154]
  [166 156 152]
  [168 157 154]
  ...
  [144 145 141]
  [146 147 142]
  [146 147 142]]]
[[[ 73  84  86]
  [ 76  84  86]
  [ 82  86  90]
  ...
  [ 53  61  46]
  [ 53  61  46]
  [ 49  57  43]]

 [[ 79  85  87]
  [ 80  85  87]
  [ 81  85  87]
  ...
  [ 54  60  53]
  [ 53  59  52]
  [ 52  58  51]]

 [[ 80  87  86]
  [ 81  87  86]
  [ 81  85  85]
  ...
  [ 54  60  54]
  [ 54  60  55]
  [ 53  59  53]]

 ...

 [[164 158 154]
  [162 158 153]
  [161 158 152]
  ..

[[[ 73  89  81]
  [ 73  85  82]
  [ 75  84  86]
  ...
  [ 56  60  54]
  [ 58  58  58]
  [ 60  59  60]]

 [[ 72  88  80]
  [ 73  86  80]
  [ 77  86  83]
  ...
  [ 53  61  52]
  [ 53  59  53]
  [ 55  61  56]]

 [[ 72  88  80]
  [ 74  87  80]
  [ 78  88  83]
  ...
  [ 52  60  48]
  [ 54  61  51]
  [ 55  62  52]]

 ...

 [[164 158 154]
  [164 158 153]
  [164 158 152]
  ...
  [140 145 143]
  [140 145 144]
  [140 145 145]]

 [[162 157 151]
  [162 157 151]
  [164 158 152]
  ...
  [139 145 140]
  [139 145 140]
  [140 146 141]]

 [[164 154 148]
  [164 157 150]
  [164 159 150]
  ...
  [138 144 138]
  [139 145 140]
  [140 146 141]]]
[[[ 85  92  84]
  [ 85  90  86]
  [ 84  89  89]
  ...
  [ 55  60  55]
  [ 54  60  55]
  [ 55  61  56]]

 [[ 85  92  84]
  [ 84  91  87]
  [ 82  89  89]
  ...
  [ 54  59  56]
  [ 54  59  58]
  [ 54  59  58]]

 [[ 83  92  84]
  [ 83  92  85]
  [ 82  90  85]
  ...
  [ 53  59  56]
  [ 52  59  58]
  [ 53  60  60]]

 ...

 [[165 159 153]
  [162 157 151]
  [162 157 151]
  ..

[[[ 84  91  93]
  [ 83  90  91]
  [ 82  89  89]
  ...
  [ 58  52  56]
  [ 61  56  59]
  [ 65  60  62]]

 [[ 84  91  91]
  [ 83  90  90]
  [ 82  89  89]
  ...
  [ 57  53  55]
  [ 61  56  59]
  [ 64  58  61]]

 [[ 83  91  86]
  [ 83  91  88]
  [ 83  90  90]
  ...
  [ 58  55  58]
  [ 60  57  60]
  [ 62  59  61]]

 ...

 [[167 158 157]
  [167 158 157]
  [167 158 157]
  ...
  [140 146 141]
  [140 146 141]
  [140 146 141]]

 [[165 158 157]
  [164 158 157]
  [163 158 158]
  ...
  [140 145 143]
  [141 146 146]
  [141 146 146]]

 [[163 157 160]
  [163 157 160]
  [163 157 160]
  ...
  [142 145 144]
  [143 146 146]
  [145 147 147]]]
[[[ 76  91  83]
  [ 74  90  82]
  [ 73  89  81]
  ...
  [ 55  61  50]
  [ 54  61  51]
  [ 56  63  54]]

 [[ 77  90  82]
  [ 76  91  83]
  [ 73  89  81]
  ...
  [ 56  61  49]
  [ 56  61  49]
  [ 57  62  50]]

 [[ 78  89  81]
  [ 77  89  81]
  [ 77  87  80]
  ...
  [ 55  61  51]
  [ 53  60  50]
  [ 53  60  50]]

 ...

 [[164 157 157]
  [162 157 155]
  [160 157 152]
  ..

[[[ 84  87  73]
  [ 85  87  73]
  [ 85  88  74]
  ...
  [ 50  60  54]
  [ 50  61  53]
  [ 52  63  55]]

 [[ 85  88  74]
  [ 84  88  74]
  [ 83  88  74]
  ...
  [ 51  60  54]
  [ 53  62  54]
  [ 54  63  55]]

 [[ 82  90  75]
  [ 81  88  76]
  [ 82  89  79]
  ...
  [ 52  59  53]
  [ 54  60  53]
  [ 55  61  54]]

 ...

 [[166 159 148]
  [166 159 150]
  [166 158 152]
  ...
  [142 143 139]
  [142 143 138]
  [142 143 138]]

 [[167 158 145]
  [167 158 146]
  [167 158 147]
  ...
  [143 143 143]
  [145 143 143]
  [146 143 143]]

 [[167 159 143]
  [164 159 144]
  [161 157 144]
  ...
  [146 145 147]
  [146 144 146]
  [146 142 145]]]
[[[ 80  87  73]
  [ 82  88  71]
  [ 85  89  71]
  ...
  [ 56  57  51]
  [ 60  60  53]
  [ 62  61  54]]

 [[ 83  90  78]
  [ 83  90  75]
  [ 83  89  72]
  ...
  [ 57  57  51]
  [ 60  60  53]
  [ 62  61  54]]

 [[ 84  92  80]
  [ 83  91  76]
  [ 81  89  72]
  ...
  [ 60  59  51]
  [ 59  58  52]
  [ 60  60  53]]

 ...

 [[166 157 154]
  [163 156 152]
  [162 156 152]
  ..

KeyboardInterrupt: 

In [17]:
path = r"E:\DEEP-LEARNING\video-classification\images\swimming"
for img in os.listdir(path):
    h,t = os.path.splitext(img)
    if t in [".jpe"]:
        print(t)