In [1]:
import numpy as np

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr = np.array([[[1,2,3,],[4,5,6]],[1,2,3]])

<ipython-input-58-8794338e0da2>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[[1,2,3,],[4,5,6]],[1,2,3]])


In [112]:
arr1 = np.array([[[
    [[1,2],[1,2],[1,2]],
    
    [[3,4],[4,5],[1,2]],
    
    [[4,5],[7,8],[1,2]],
    
    [[4,5],[7,8],[1,2]]]
    
                ]])

In [113]:
arr1.ndim

5

In [153]:
arr2 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
arr2.ndim


3

In [155]:
arr2[:1,:1,:] #[1st mat,1st row, every col]

array([[[1, 2, 3]]])

In [160]:
arr2[:,:,:1]  #[1st mat,1st row, every col]

array([[[1],
        [4],
        [7]]])

In [163]:
arr2[:,:,1:2] = 0
arr2

array([[[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]]])

# Math operations

In [165]:
foo = np.array([[1,2,3],[3,4,5]])
bar = np.array([[2,1,4],[3,5,7]])

In [168]:
sub = foo - bar
add = foo + bar

In [207]:
wt = 185-np.arange(7*5)/5
print(wt)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [211]:
(wt[5::7] + wt[6::7])/2  

array([183.9, 182.5, 181.1, 179.7, 178.3])

# nd array

In [219]:
ndarr=np.ndarray(shape=(2,6),dtype="int64")
print(ndarr)

[[      1143545456152                  64                   0
                    0                   0 3919648144563450673]
 [4048792557620651619 3559639437375059555 7003159415028791140
  3545795498569251174 7365700284462477875 7075265186522870320]]


In [224]:
ndarr[1][1::2]

array([3559639437375059555, 3545795498569251174, 7075265186522870320],
      dtype=int64)

In [239]:
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [245]:
np.ndarray(shape=(2,),buffer = np.array([1,2,3,4,5]))

array([4.24399158e-314, 8.48798317e-314])