In [1]:
import numpy as np
import array

In [2]:
arr = np.array([(1,3),(3,4)],dtype = [("a",'<i4'),("b",'<i8')])

In [3]:
arr1=np.array([[[1,2]],[[2,3]],[[3,4]]])

In [4]:
type(arr[0][0])

numpy.int32

In [5]:
type(arr[0][1])

numpy.int64

In [6]:
arr1[0]

array([[1, 2]])

In [7]:
arr1[1][0]

array([2, 3])

In [8]:
matrix = np.mat(arr1)

In [9]:
l = [1,2,3,4]

In [10]:
np.array(l)

array([1, 2, 3, 4])

In [11]:
np.asarray(l)

array([1, 2, 3, 4])

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [13]:
np.asanyarray(matrix)

matrix([[1, 2],
        [2, 3],
        [3, 4]])

In [14]:
a = arr  #shallow copy
b = np.copy(arr)  #deep copy

In [15]:
arr[0][0] = 100

In [16]:
arr

array([(100, 3), (  3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [17]:
b

array([(1, 3), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [18]:
a

array([(100, 3), (  3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [19]:
arr.ndim

1

In [20]:
arr.size

2

In [21]:
arr.shape

(2,)

In [22]:
arr[0][1]

3

In [23]:
arr1.shape

(3, 1, 2)

In [24]:
arr1

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [25]:
np.linspace(2,4,4,axis = 0)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [26]:
np.linspace([2,4],4,axis =1 )

array([[2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
        2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
        2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
        2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
        2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
        3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
        3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
        3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
        3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
        3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ],
       [4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4.        , 4.        ,
        4.        , 4.        , 4.        , 4. 

In [27]:
np.logspace(1,2,1,20)

array([10.])

In [28]:
arr1.reshape(2,1,20)

ValueError: cannot reshape array of size 6 into shape (2,1,20)

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.randn(3)

In [ ]:
np.random.randint(3,30)

In [ ]:
np.random.randint(3,30,(3,3))

In [ ]:
arr2 = np.random.randint(3,9,(4,4))

In [ ]:
arr2

In [ ]:
arr2.max()

In [ ]:
arr2.min()

In [ ]:
arr3 = np.random.randint(4,100,(5,5))

In [ ]:
arr3

In [ ]:
arr3[3:,3:]

In [ ]:
arr3[1:4,1:4]

In [ ]:
arr3[arr3<0]

In [ ]:
arr3*arr3

In [31]:
arr

array([(100, 3), (  3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])