In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import joblib

In [30]:
class preceptron:
    def __init__(self,epochs: int=None,eta:float=None):
        self.weight = np.random.randn(3) *1e-4
        self.eta = eta
        self.epochs = epochs
        
    def fit(self,X,y):
        self.X = X
        self.y = y
        self.X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        #print(f"X_with_bias: \n{self.X_with_bias}")
        
        
        

In [31]:
obj = preceptron(eta = 0.01,epochs = 100)
obj.weight

array([1.39560702e-04, 7.08880850e-05, 1.68409945e-05])

In [32]:
X = np.ones((4,2))
y = np.ones((4,1))

In [33]:
obj.fit(X,y)

X_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
